# Generated by Django 5.1.1 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentregistered",
            options={
                "verbose_name": "Student Registered",
                "verbose_name_plural": "Students Registered",
            },
        ),
        migrations.AlterModelTable(
            name="studentregistered",
            table="students_registered",
        ),
    ]
