# Generated by Django 5.1.1 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="material",
            options={"verbose_name": "Material", "verbose_name_plural": "Materials"},
        ),
        migrations.AlterModelTable(
            name="course",
            table="courses",
        ),
        migrations.AlterModelTable(
            name="material",
            table="materials",
        ),
    ]
