# Generated by Django 5.1.1 on 2024-09-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_alter_course_options_alter_material_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="is_quiz_generated",
            field=models.BooleanField(default=False),
        ),
    ]
