# Generated by Django 5.1.1 on 2024-11-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_material_is_quiz_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/courses"),
        ),
    ]
