# Generated by Django 5.1.1 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={"verbose_name": "Program", "verbose_name_plural": "Programs"},
        ),
        migrations.AlterModelTable(
            name="program",
            table="programs",
        ),
    ]
