# Generated by Django 5.1.1 on 2024-11-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0002_alter_program_options_alter_program_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/programs"),
        ),
    ]
