# Generated by Django 5.1.1 on 2024-09-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_user_date_of_birth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainerpermission",
            options={
                "verbose_name": "Trainer Permission",
                "verbose_name_plural": "Trainer Permissions",
            },
        ),
        migrations.AlterModelTable(
            name="trainerpermission",
            table="trainers_permissions",
        ),
    ]
