# Generated by Django 5.1.1 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name": "Quiz", "verbose_name_plural": "Quizes"},
        ),
        migrations.AlterModelOptions(
            name="quizanswer",
            options={
                "verbose_name": "Quiz Answer",
                "verbose_name_plural": "Quiz Answers",
            },
        ),
        migrations.AlterModelTable(
            name="quiz",
            table="quizes",
        ),
        migrations.AlterModelTable(
            name="quizanswer",
            table="quiz_answers",
        ),
    ]
