# Generated by Django 5.1.1 on 2024-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quiz_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quiz",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
