# Generated by Django 5.1.1 on 2024-12-17 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "question",
            "0002_alter_question_options_alter_questionanswer_options_and_more",
        ),
        ("quiz", "0004_quiz_score_quiz_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizanswer",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.questionanswer",
            ),
        ),
    ]
